export const DATABASE_URL_ENV = process.env.DATABASE_URL || ""
export const RESEND_API_KEY_ENV = process.env.RESEND_API_KEY || ""
export const RESEND_EMAIL_ENV = process.env.RESEND_EMAIL || ""
export const GOOGLE_CLIENT_ID_ENV = process.env.GOOGLE_CLIENT_ID || ""
export const GOOGLE_CLIENT_SECRET_ENV = process.env.GOOGLE_CLIENT_SECRET || ""
export const GITHUB_CLIENT_ID_ENV = process.env.GITHUB_CLIENT_ID || ""
export const GITHUB_CLIENT_SECRET_ENV = process.env.GITHUB_CLIENT_SECRET || ""
export const BETTER_AUTH_URL_ENV = process.env.BETTER_AUTH_URL || ""
export const AWS_ACCESS_KEY_ID_ENV = process.env.AWS_ACCESS_KEY_ID || ""
export const AWS_SECRET_ACCESS_KEY_ENV = process.env.AWS_SECRET_ACCESS_KEY || ""
export const AWS_REGION_ENV = process.env.AWS_REGION || ""
export const S3_UPLOAD_BUCKET_ENV = process.env.S3_UPLOAD_BUCKET || ""
export const UPSTASH_REDIS_REST_URL_ENV = process.env.UPSTASH_REDIS_REST_URL || ""
export const UPSTASH_REDIS_REST_TOKEN_ENV = process.env.UPSTASH_REDIS_REST_TOKEN || ""

// PUBLIC
export const NEXT_PUBLIC_APP_URL_ENV = process.env.NEXT_PUBLIC_APP_URL || ""
